-- MySQL Script generated by MySQL Workbench
-- 01/05/16 16:23:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fundispenser_server
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fundispenser_server
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fundispenser_server` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `fundispenser_server` ;

-- -----------------------------------------------------
-- Table `fundispenser_server`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fundispenser_server`.`subjects` (
  `subjectId` INT NOT NULL AUTO_INCREMENT,
  `subjectName` VARCHAR(45) NULL,
  PRIMARY KEY (`subjectId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fundispenser_server`.`flavours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fundispenser_server`.`flavours` (
  `flavourId` INT NOT NULL AUTO_INCREMENT,
  `flavourName` VARCHAR(45) NULL,
  PRIMARY KEY (`flavourId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fundispenser_server`.`levels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fundispenser_server`.`levels` (
  `levelId` INT NOT NULL AUTO_INCREMENT,
  `achievedAt` INT NULL,
  `levelName` VARCHAR(45) NULL,
  PRIMARY KEY (`levelId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fundispenser_server`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fundispenser_server`.`players` (
  `playerId` INT NOT NULL AUTO_INCREMENT,
  `playerName` VARCHAR(45) NULL,
  `tagID` VARCHAR(45) NULL,
  `experience` INT NULL,
  `levelId` INT NOT NULL,
  `flavourId` INT NOT NULL,
  PRIMARY KEY (`playerId`),
  INDEX `fk_players_flavours_idx` (`flavourId` ASC),
  INDEX `fk_players_levels1_idx` (`levelId` ASC),
  CONSTRAINT `fk_players_flavours`
    FOREIGN KEY (`flavourId`)
    REFERENCES `fundispenser_server`.`flavours` (`flavourId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_players_levels1`
    FOREIGN KEY (`levelId`)
    REFERENCES `fundispenser_server`.`levels` (`levelId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fundispenser_server`.`difficulty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fundispenser_server`.`difficulty` (
  `playerSkill` INT(2) NULL,
  `subjectId` INT NOT NULL,
  `levelId` INT NOT NULL,
  INDEX `fk_difficulty_subjects1_idx` (`subjectId` ASC),
  INDEX `fk_difficulty_levels1_idx` (`levelId` ASC),
  CONSTRAINT `fk_difficulty_subjects1`
    FOREIGN KEY (`subjectId`)
    REFERENCES `fundispenser_server`.`subjects` (`subjectId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_difficulty_levels1`
    FOREIGN KEY (`levelId`)
    REFERENCES `fundispenser_server`.`levels` (`levelId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fundispenser_server`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fundispenser_server`.`questions` (
  `questionId` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(128) NULL,
  `subjectId` INT NOT NULL,
  PRIMARY KEY (`questionId`),
  INDEX `fk_questions_subjects1_idx` (`subjectId` ASC),
  CONSTRAINT `fk_questions_subjects1`
    FOREIGN KEY (`subjectId`)
    REFERENCES `fundispenser_server`.`subjects` (`subjectId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fundispenser_server`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fundispenser_server`.`answers` (
  `answerId` INT NOT NULL AUTO_INCREMENT,
  `answer` VARCHAR(45) NULL,
  `questionId` INT NOT NULL,
  PRIMARY KEY (`answerId`),
  INDEX `fk_answers_questions1_idx` (`questionId` ASC),
  CONSTRAINT `fk_answers_questions1`
    FOREIGN KEY (`questionId`)
    REFERENCES `fundispenser_server`.`questions` (`questionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
